### PR TITLE
Dev music

### PR DESCRIPTION
**Pull request by jmmelko**

### CODE REVIEW

**Comment by e-a-h** [comment]
I've tried this with all branches of sky-python-music-sheet-maker and can not successfully run through the dialog. Is there a specific commit I should have checked out for this to function?

**Comment by jmmelko** [comment]
Hello Alex,
Thanks for trying.

Actually I have created this pull request weeks ago, so in the meantime I have dropped all expectations that it would be addressed one day. So I made some refactoring in the music maker code instead.

I will straighten things. Shouldn’t take me long.

Feel free to close this pull request, I will create another one.

Thank you.

jmmelko

**Comment by e-a-h** [comment]
ok, sorry for the delayed review. I couldn't merge for a while because language refactoring was in progress. I have localization mostly functional now, and have replaced "Lang.get_string" with "Lang.get_locale_string." get_locale string has an additional "context" parameter, which can either be a discord.commands.context or a string matching one of the supported locales, or "ALL_LOCALES" for broadcasting in all languages.

**Comment by jmmelko** [comment]
Alex,

I have repaired the music cog.
The working branch is ‘dev’.

I have not yet updated the code to match your changes on locales, but you can give it a try anyway.

Thank you.

**Comment by jmmelko** [comment]
OK, I have added the locale by:
- loading the LangConfig cog
- calling the getdefaultedlocale in the Music Cog

I’ll leave the rest to you.

I’m looking forward to seeing the cog running before I die.

**Comment by e-a-h** [comment]
> I’m looking forward to seeing the cog running before I die.

I guess I deserved that :D 

Since android launch I've become very busy, and the bot has also become pretty busy. I've slowly working to stabilize some things and had issues with the bot crashing for a little while, so was moving slowly to avoid causing mayhem in the sever.

**Comment by jmmelko** [comment]
It is true that a faulty cog can make the whole bot to hang or crash, this scares me a lot!

**Comment by e-a-h** [comment]
a faulty cog *could* make the bot crash, or could potentially just unload. but that's why I review and test :D

**Comment by e-a-h** [comment]
A couple problems in testing still:
- the aspect ratio prompt doesn't quite work. it says "leave blank" for default but you can't answer with blank
- Aspect ratio is expressed as a fraction, 16/9 as opposed to a ratio 16:9. It will be confusing to most people no matter what format is expected. This might work better as multiple choice with examples, like:
  1. 16:9 - wide like a TV   [___]
  1. 4:3 - like... an old TV  [__]
  1. 1:1 - square                  [_]
  **or** enter a custom aspect ratio as a fraction, e.g. 16/9
- Name entry: it's ok for now, but I think I'd like to rewrite the dialog as a single prompt with multiple reaction choices for optionally entering Name or auto-entering discord name+discriminator+maybe discord ID. Composer should be required, arranged by should be an option, transcribed by should be an option.

**Comment by e-a-h** [comment]
Regarding branches, I request that the music sheet maker repo have a release-skybot branch so it's always clear what the stable version for skybot integration is. Unless the master branch is always intended to be stable for both skybot and standalone use...

And I'm not clear on how localization handoff should work between skybot-hosted language strings and those written into the music sheet maker. In terms of discord dialogs I'd like to have *some* control over the language presented to users, but I haven't thought through the best approach to this yet.

**Comment by e-a-h** [comment]
AND another thing: licensing. This may get tricky so maybe it's a discussion for another day, but might want to include license options to show permissions for sharing between sites and apps. creative commons licenses are pretty clear and easy to use, so we might start there. The biggest challenge is in applying a license to preexisting commercial music.

**Comment by e-a-h** [comment]
re: 10 file limit... maybe we can zip multiple files. If the 10 file limit is there because 10 attachment limit in discord, then we can also iterate and send multiple messages... but I would prefer auto-zip for more than 10. Maybe auto-zip for more than 5 even... or some reasonable number of sheets. what do you think?

**Comment by jmmelko** [comment]
I don’t think you Question model allows to answer either by a reaction or a string. 
I mean, you have Question.ask_text which expects a string and and Question.ask which expects a reaction but not a combination of the two.
This would be very useful for me. Not only for aspect ratio but for other questions as well.

**Comment by e-a-h** [comment]
I've modeled that style of questioning in dev-art-collector branch. We can make that change, or just try address other issues to get it into production and restructure question flow later.

**Comment by e-a-h** [comment]
logging from test run yesterday if it's useful.
[music_logs.txt](https://github.com/e-a-h/That-Sky-Bot/files/4707650/music_logs.txt)

**Comment by e-a-h** [comment]
I added zip file output for 4+ sheets. In testing though, it seemed I was only able to get 11 sheets total. Is there a limit in music sheet maker on how many files are output? Or how much time the output takes? I think there should be some limit set so the bot can't be intentionally hijacked with long songs, but I'm not sure what the best approach should be.

**Comment by jmmelko** [comment]
Yes,

I have internally set the maximum number of pages to 11.

JMM.

**Comment by jmmelko** [comment]
‘If I'm understanding correctly, then I think octave shift should be disabled for sky keyboard entry styles. Entering octave shifts for almost any entry done as sky keyboard results unusable notes and red question marks.‘

What are you talking about?

Octave shift is NOT proposed for Sky and Sky keyboard entries.

If you encountered this, then it means either that there is a bug, or that the program detected/thought you were using another musical notation.

If so, could you please write down the steps to reproduce the bug?

Thank you.

**Comment by e-a-h** [comment]
I entered q w e r t etc. as my music. I'm prompted for key, and then prompted for octave shift.

**Comment by jmmelko** [comment]
Oops, you’re right, I had left this and nobody complained.
It fixed this and aspect ratio also.
I will test it locally and then pull this to a new branch as asked.
I have not addressed copyright and other trick stuff yet.

**Comment by e-a-h** [comment]
regarding max sheets: if you think 11 is a reasonable maximum based on songs you've entered or seen entered, I'm ok with that. Can the sheet maker possibly also return a message or flag if the song overruns 11 sheets though, so we can inform people when their songs are truncated?

**Comment by jmmelko** [comment]
Ok, here is what I have done:

* fixed the aspect ratio question
* fixed the blank answer issue
* fixed the octave issue
* made artist mandatory, other meta data optional. Is it ok or do you really *really* want to add "arranged by"?

You can test again using the dev branch

Here are the immediate TODOs:

- [ ] Create a skybot-release branch. I have to ask Tracey about that, because initially we intended to have a universal master branch, but pulling from dev to master can take some time
- [ ] Add emojis for aspect_ratio (cosmetical)

Later TODOs:

- [ ] Change question flow to be able to answer with either an emoji or a text
- [ ] address copyright
- [ ] Address "conflict" between bot Lang and music Maker Lang => I think you can directly change the text in the .yaml files yourself, unless you want to add "Discord specific" text for some questions, in that case please consult me about that
- [ ] 'name entry' with discord name+discriminator+maybe discord ID: do you mean file name? treating this question differently

**Comment by e-a-h** [comment]
Thank you, I'll pull the latest and stand it up for testing again. I'll add concurrency test shortly. 

"Arranged by" is just an "nice to have" item. I'm only thinking about interaction between other music apps and making sure we have a format of data that is portable and standardized.

Release branch is only necessary if head of master branch is *not* intended to be universal.

for language files, as long as we can pass locale from the bot dialog into the music sheet maker and have sheet maker respond in the same language, I'm ok. I decided on a list as return type from get_defaulted_locale because there are some channels in the server that will be universal and will need response in every available language. like the welcome channel. But bot dialog should generally only be in one language, and I might add that as question #1

Copyright is not a priority for me right now, but is mostly for future thinking, sharing between apps, and sharing outside the Sky server.

**Comment by e-a-h** [comment]
New issue after I pulled the latest in the dev branch. This happens when choosing a key after entering sky notation, qwert or a1b2c3. I can make it past that step if I check out the commit before.

https://sentry.io/share/issue/50396bac954e47cfb09ba3fdb54476fa/

**Comment by jmmelko** [comment]
Sorry, I had forgotten to push the new code for the Music Cog.
(Incidentally It helped me find a serious typo in my code :-) )

JMM.

**Comment by jmmelko** [comment]
Alex,

By “master branch”, do you mean the default branch?
I am asking because I am planning to name the default branch “stable” and let “master” the branch to be used by the music cog and the website, but I don’t know if it’s suitable for you.

Tx.

**Comment by e-a-h** [comment]
re: branches I'll rephrase. I'm not in charge of how you branch so do what makes the most sense for you; don't let me throw a wrench in your plans! As long as it's clear which commit the bot should be using, I'm ok.

**Comment by jmmelko** [comment]
Alex,

the branch to use is now 'master'.

What do you mean by "name entry with discord name+discriminator+maybe discord ID"
Like an automatic file name: SongTitle_alexdolly_azjkdnj_#0001 ?

TODOs:
    

- [ ] Add emojis for aspect_ratio (cosmetical)
- [ ] change question flow to be able to answer with either an emoji or a text
- [ ] address copyright
- [X] Address "conflict" between bot Lang and music Maker Lang => My Lang was directly modeled after yours, so it behaves similarly. You are welcome to improve the text in the .yaml files yourself. If you need to to add "Discord specific" instructions (for instance "please answer with an emoji"), then tell me so and I will make the change (since this requires feeding a new dictionary item to a .format instruction inside the code)
- [ ] 'name' entry with discord name+discriminator+maybe discord ID: do you mean file name?

**Comment by e-a-h** [comment]
name entry I'm committing a semi-functional example in cogs/Music.py - I intended it to convert user id or user mention into a nice display name, but it looks like mentions are escaped or something, and I'm too tired to see where right now :) ... will fix tomorrow or so unless you want to take a crack at fixing it. For testing just the name conversion, you can use `?name_test @alexdolly` (make sure the name you use completes as a mention... maybe mention yourself) and `?name_test 295762764234752000` where the number is a user id.

**Comment by e-a-h** [comment]
Sheets in every format appear to have one trailing keyboard. In some cases it results in extra white space. In other cases it results in the board getting cut off.

1. should be corrected so a full sheet doesn't have one trailing
1. maybe verify that all available aspect ratios result in nicely lined-up rows that fill the space well.

asdf_000

**Comment by jmmelko** [comment]
Actually this only happens if you type a very long line, which we advised against from the very beginning.
Recently I found a way to render long lines, but it seems that I did not fully tested it.
I will fix it.

**Comment by e-a-h** [comment]
there are no directions in the discord implementation currently that I can see indicating line breaks. I also advise against even *mentioning* line breaks to discord users because they will hit "enter" and prematurely end note input. then mods will get endless mentions asking how to input more music after making a line break!!

So yes, I fully endorse long-line rendering. None of my testing so far as involved using line breaks, so i should try that :D

**Comment by jmmelko** [comment]
OK, it’s fixed now (it was because point 0,0 in images is the top left corner, not the bottom right...)

Actually users can enter the song line by line because the program loops over the “enter notes” question, but I agree that this implicit and confusing.

**Comment by t1-tracey** [comment]
What’s the status of this?

**Comment by e-a-h** [comment]
> What’s the status of this?

At the moment it's blocked by some other tasks I have for fixing things in the bot. I'll get back onto it as soon as I can.

**Comment by jmmelko** [comment]
It will take me several days to believe this actually happens :-))

Just a question: will the bot be only triggered by !song? Or can we add listening keywords to suggest to users to use the maker? I mean, just like the bot sometimes say something when someone talks about  Eden.
I don’t want to spam the forum but I thought that maybe some kind of subtle, soft advertising might be necessary.

**Comment by e-a-h** [comment]
music sheet maker is live in sky official server now. you can try it yourself.

at the moment, !song is the only trigger. it's possible to add autoresponders or commands with instructions, but I don't want to push it too hard at first in case it runs into unforeseen trouble in its debut. I will also likely add a special reaction trigger for it as well.... later.

**Pull request merged**
